### ISSUE TITLE
Revisit use of cegis IRIs

### ISSUE THREAD

**Issue by amoeba** [DataONEorg/usgs-triplifier#14]
For each feature in GNIS-LD, we have a triple that reference a `cegis` namespace, see:

```ttl
@prefix gnisf: <https://gnis-ld.org/lod/gnis/feature/> .
@prefix cegis: <https://gnis-ld.org/lod/cegis/ontology/> .    

gnisf:26407 a cegis:Summit .
```

It sounds like there was at one point an ontology for terms in this `cegis` namespace but we no longer have it. It had something to do with https://www.usgs.gov/core-science-systems/ngp/cegis/geospatial-semantics-and-ontology?qt-science_support_page_related_con=1#qt-science_support_page_related_con. 

We _do_ have two other ontologies, a GNIS-LD one and a USGS one. The classes referenced in the `cegis` namespace look very similar to the classes in the USGS ontology and why that is isn't clear to me.

My preference for the features in GNIS-LD would be that...

1. Their types resolve to terms in an ontology we do have
2. Their types are superclassed to something in a common geospatial vocab like `geosparql:Feature` or `geosparql:SpatialObject`. This seems important for integration with projects like KWG or Slinky.

There are many ways beyond the two points above to improve GNIS-LD but I think they're out of scope for our work here at the moment.

Do others agree with my preferences here? I can think of some next steps:

1. Re-create an ontology to describe the cegis terms. Most (if not all) of these already exist in the USGS ontology
2. Re-triplify everything to use just the USGS and GNIS ontologies

I'm leaning towards (2) unless someone points out a big issue.

**Comment by ThomasThelen** [comment]
(2) sounds great to me, assuming that we're fine with mutating the USGS ontology (which I think sounds fine).

Tasks:
- [x] Replace cegis types with USGS types
- [ ] Add geosparql:Feature or geosparql:SpatialObject as superclasses to relevant GNIS types

**Comment by amoeba** [comment]
We brought this up on our salmantics call @ThomasThelen is going to email Dalia from the CEGIS group to ask about this namespace and run the idea of switching all the CEGIS terms to GNIS-USGS terms.

**Comment by ThomasThelen** [comment]
After an email thread with @dvaranka, 

1. We should stick with the current USGS ontology we have (although in the future, The USGS may release an official ontology)
2. CEGIS appears to be a missing ontology; switching terms over to USGS should be okay. 

I'm adding this to the 2.1.0 milestone

**Comment by ThomasThelen** [comment]
Done in #25
